### ISSUE TITLE
add ci/cd actions

### ISSUE THREAD

**Issue by navanjr** [amplify-technologies/lawns-website#1]
This site is hosted on DigitalOcean. 
This will require [`action-doctl`](https://github.com/digitalocean/action-doctl)
Here are the details: https://www.digitalocean.com/community/tech-talks/deploying-to-digitalocean-with-github-actions

however, we don't want to create a new droplet. Instead we will want to stop and restart the docker image on littlebird. like we do here: https://gitlab.com/inkbird.io/clients/amp/-/blob/master/.gitlab-ci.yml#L30

**Comment by joshandersn** [comment]
This is done! closing issue...
